/**
 * [dz.gov.mesrs.sii.fve.business.model.bo.cursus.AssociationGroupePedagogique.java] 
 * @author MAKERRI Sofiane on : 2 oct. 2014  09:46:00
 */
package dz.mesrs.progres.rest.modal.cursus;



import dz.mesrs.progres.rest.modal.lmd.AtomePedagogique;
import dz.mesrs.progres.rest.modal.groupe.GroupePedagogique;
import dz.mesrs.progres.rest.modal.lmd.RattachementMc;
import lombok.Data;

import javax.persistence.*;
import java.util.Date;

/**
 * GroupePedagogiqueAp generated by hbm2java
 */
@Data
@Entity
@Table(name = "association_groupe_pedagogique", schema = "cursus", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_groupe_pedagogique", "id_rattachement_mc", "id_ap" }))
public class AssociationGroupePedagogique implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id",insertable=false, updatable=false)
	private int id;
	@ManyToOne
	@JoinColumn(name = "id_groupe_pedagogique", nullable = false)
	private GroupePedagogique groupePedagogique;
	@ManyToOne
	@JoinColumn(name = "id_ap", nullable = false)
	private AtomePedagogique ap;
	@Column(name = "obervation", length = 500)
	private String obervation;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_attachement", length = 29)
	private Date dateAttachement;
	@ManyToOne
	@JoinColumn(name = "id_rattachement_mc", nullable = false)
	private RattachementMc rattachementMc;

}
